# Generated by Django 5.0.3 on 2024-04-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=15)),
                ('schoolClass', models.CharField(max_length=5)),
                ('telegramId', models.IntegerField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('fullname', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('motto', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
