# Generated by Django 5.0.3 on 2024-04-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
